# Generated by Django 2.1 on 2019-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.IntegerField()),
                ('region_name', models.TextField()),
                ('dept_code', models.TextField()),
                ('distr_code', models.IntegerField()),
                ('code', models.IntegerField()),
                ('name', models.TextField()),
                ('population', models.IntegerField()),
                ('average_age', models.FloatField()),
            ],
        ),
    ]
